name: Build and Push Docker Images to ECR

on:
  push:
    branches:
      - shopsphere-App
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: "136609826386"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configurer les credentials AWS via OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::136609826386:role/shopsphere-eks-GitHubActionsECRRole
          aws-region: ${{ env.AWS_REGION }}

      # 3. Se connecter à ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 4. Activer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5. Build & Push user-service
      - name: Build and push user-service
        uses: docker/build-push-action@v6
        with:
          context: ./user-service
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/shopsphere-user-service:latest
          cache-from: type=gha,scope=user-service
          cache-to: type=gha,mode=max,scope=user-service

      # 6. Build & Push product-service
      - name: Build and push product-service
        uses: docker/build-push-action@v6
        with:
          context: ./product-service
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/shopsphere-product-service:latest
          cache-from: type=gha,scope=product-service
          cache-to: type=gha,mode=max,scope=product-service

      # 7. Build & Push order-service
      - name: Build and push order-service
        uses: docker/build-push-action@v6
        with:
          context: ./order-service
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/shopsphere-order-service:latest
          cache-from: type=gha,scope=order-service
          cache-to: type=gha,mode=max,scope=order-service

      # 8. Build & Push cart-service
      - name: Build and push cart-service
        uses: docker/build-push-action@v6
        with:
          context: ./cart-service
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/shopsphere-cart-service:latest
          cache-from: type=gha,scope=cart-service
          cache-to: type=gha,mode=max,scope=cart-service

      # 9. Build & Push notification-service
      - name: Build and push notification-service
        uses: docker/build-push-action@v6
        with:
          context: ./notification-service
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/shopsphere-notification-service:latest
          cache-from: type=gha,scope=notification-service
          cache-to: type=gha,mode=max,scope=notification-service

      # 10. Build & Push api-gateway
      - name: Build and push api-gateway
        uses: docker/build-push-action@v6
        with:
          context: ./api-gateway
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/shopsphere-api-gateway:latest
          cache-from: type=gha,scope=api-gateway
          cache-to: type=gha,mode=max,scope=api-gateway

      # 11. Build & Push frontend
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/shopsphere-frontend:latest
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend